name = "url-shortner-sarcastic"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "url-shortner-db"
database_id = "auto"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "sarcastic-images"

[vars]
JWT_SECRET = "my-super-secret-key-change-this-12345"